### ISSUE TITLE
LYRICS NOT VISIBLE IN FULL SCREEN

### ISSUE THREAD

**Issue by Himesh444** [Oein/beautifulfullscreen#1]
when i open beautiful lyrics . first it open in windowed mode then when i press F to make it full screen the lyrics just disappears. In options i have turned on show lyrics but it didn't work. I tried turning show lyrics on and off but it also didn't work. i have updated everything and installed as it is written in marketplace. i have installed theme named Bloom. I have attached images as reference . pls fix

![Screenshot (44)](https://github.com/Oein/beautifulfullscreen/assets/101036118/17d34a49-9941-458a-a1fb-ae3c52393aa3)
![Screenshot (45)](https://github.com/Oein/beautifulfullscreen/assets/101036118/1e2e1a88-9862-42a8-afe3-ddb63350d731)
![Screenshot (46)](https://github.com/Oein/beautifulfullscreen/assets/101036118/10ac4096-b222-4152-98a2-e913f2728c30)

**Comment by Oein** [comment]
I don't know why it happens. But I thinks it happens because Lyrics-Plus doesn't loaded because my code doesn't called `requestLyricsPlus`. This issue might be fixed on [c3b524](https://github.com/Oein/beautifulfullscreen/commit/c3b524c9a63247592e9cabbcc04853ce9359505b) by changing the way calls `requestLyricsPlus`

**Comment by livejamie** [comment]
> I don't know why it happens. But I thinks it happens because Lyrics-Plus doesn't loaded because my code doesn't called `requestLyricsPlus`. This issue might be fixed on [c3b524](https://github.com/Oein/beautifulfullscreen/commit/c3b524c9a63247592e9cabbcc04853ce9359505b) by changing the way calls `requestLyricsPlus`

Are you going to publish the fix?

**Comment by Oein** [comment]
I already published [commit c3b524 - diff df2a17](https://github.com/Oein/beautifulfullscreen/commit/c3b524c9a63247592e9cabbcc04853ce9359505b#diff-df2a174f100b2ddc531b4bd8e486101721acd5d42857b9630da8a62260baf51a)

**Comment by livejamie** [comment]
The issue was fixed for me by manually installing lyrics-plus, which isn't in the marketplace.

`spicetify config custom_apps lyrics-plus
`

**Comment by pieroltmr** [comment]
como lo instalo?

**Comment by yungestdev** [comment]
still, it seems to still not be working, not even installing from the repo and manually installing lyrics-plus. any new fix?

**Comment by evacnnn** [comment]
yeah i already installed it but it's doesn't work

**Comment by yungestdev** [comment]
for anyone having this issue rn: Align the music to the left, enable vertical mode, enable 'with lyrics sized music'

**Comment by Oein** [comment]
Beautifulfullscreen also supports [ivLyrics](https://ivlis.kr/ivLyrics/). You could also try another lyrics-plus provider.
